apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cma-rapidast-integration-test
spec:
  description: |
    Integration test that provisions an ephemeral Hypershift cluster, deploys the
    Custom Metrics Autoscaler Operator bundle from a Konflux snapshot, and runs
    RapiDAST security scanning against the operator endpoints.
  params:
  - description: Snapshot of the application containing the operator bundle
    name: SNAPSHOT
    type: string
  - description: Namespace where the operator bundle will be deployed
    name: NAMESPACE
    default: openshift-keda
    type: string
  - description: Duration to wait for bundle installation to complete before failing
    name: INSTALL_TIMEOUT
    default: 10m
    type: string
  tasks:
  - name: extract-bundle-image
    taskSpec:
      params:
      - name: SNAPSHOT
        type: string
      results:
      - name: bundle-image
        description: Bundle image extracted from snapshot
      steps:
      - name: extract-image
        image: quay.io/konflux-ci/konflux-test:latest
        env:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
        script: |
          #!/bin/bash
          set -euxo pipefail
          echo "Extracting bundle image from snapshot..."
          BUNDLE_IMAGE=$(echo "$SNAPSHOT" | jq -r '(.spec.components[]? // .components[]?) | select(.name | test(".*bundle.*"; "i")) | .containerImage' | head -1)
          if [ -z "$BUNDLE_IMAGE" ] || [ "$BUNDLE_IMAGE" = "null" ]; then
            BUNDLE_IMAGE=$(echo "$SNAPSHOT" | jq -r '(.spec.components[]? // .components[]?) | select(.name == "custom-metrics-autoscaler-operator-bundle") | .containerImage')
          fi
          if [ -z "$BUNDLE_IMAGE" ] || [ "$BUNDLE_IMAGE" = "null" ]; then
            echo "ERROR: No bundle image found"
            echo "Available components:"
            echo "$SNAPSHOT" | jq -r '(.spec.components[]? // .components[]?)?.name' | sed 's/^/  - /'
            exit 1
          fi
          echo "Found bundle image: $BUNDLE_IMAGE"
          echo -n "$BUNDLE_IMAGE" | tee "$(results.bundle-image.path)"
    params:
    - name: SNAPSHOT
      value: $(params.SNAPSHOT)
  - name: provision-eaas-space
    runAfter:
    - extract-bundle-image
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions.git
      - name: revision
        value: main
      - name: pathInRepo
        value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
    params:
    - name: ownerName
      value: $(context.pipelineRun.name)
    - name: ownerUid
      value: $(context.pipelineRun.uid)
  - name: provision-cluster
    runAfter:
    - provision-eaas-space
    taskSpec:
      results:
      - name: clusterName
        value: "$(steps.create-cluster.results.clusterName)"
      steps:
      - name: get-supported-versions
        ref:
          resolver: git
          params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
        params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
      - name: pick-version
        ref:
          resolver: git
          params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
        params:
        - name: prefix
          value: "$(steps.get-supported-versions.results.versions[0])."
      - name: create-cluster
        ref:
          resolver: git
          params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
        params:
          - name: eaasSpaceSecretRef
            value: $(tasks.provision-eaas-space.results.secretRef)
          - name: version
            value: "$(steps.pick-version.results.version)"
          - name: imageContentSources
            value: |
              - mirrors:
                - registry.stage.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-operator-bundle
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator-bundle
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator/custom-metrics-autoscaler-operator-bundle
                source: registry.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-operator-bundle
              - mirrors:
                - registry.stage.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-adapter-rhel9
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator/keda-adapter
                - quay.io/redhat-user-workloads/cma-podauto-tenant/keda-adapter
                source: registry.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-adapter-rhel9
              - mirrors:
                - registry.stage.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-admission-webhooks-rhel9
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator/keda-webhooks
                - quay.io/redhat-user-workloads/cma-podauto-tenant/keda-webhooks
                source: registry.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-admission-webhooks-rhel9
              - mirrors:
                - registry.stage.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-rhel9-operator
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator/custom-metrics-autoscaler-operator
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator
                source: registry.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-rhel9-operator
              - mirrors:
                - registry.stage.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-rhel9
                - quay.io/redhat-user-workloads/cma-podauto-tenant/custom-metrics-autoscaler-operator/keda-operator
                - quay.io/redhat-user-workloads/cma-podauto-tenant/keda-operator
                source: registry.redhat.io/custom-metrics-autoscaler/custom-metrics-autoscaler-rhel9

  - name: deploy-operator
    runAfter:
    - provision-cluster
    params:
    - name: bundleImage
      value: "$(tasks.extract-bundle-image.results.bundle-image)"
    - name: namespace
      value: "$(params.NAMESPACE)"
    - name: installTimeout
      value: "$(params.INSTALL_TIMEOUT)"
    taskSpec:
      params:
      - name: bundleImage
        type: string
      - name: namespace
        type: string
      - name: installTimeout
        type: string
      volumes:
      - name: credentials
        emptyDir: {}
      steps:
      - name: get-kubeconfig
        ref:
          resolver: git
          params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
        params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: credentials
          value: credentials
      - name: create-namespace
        image: quay.io/konflux-ci/konflux-test:latest
        env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
        - name: NAMESPACE
          value: "$(params.namespace)"
        volumeMounts:
        - name: credentials
          mountPath: /credentials
        script: |
          #!/bin/bash
          set -euxo pipefail
          echo "Creating namespace: $NAMESPACE"
          oc create namespace "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -
          echo "Namespace $NAMESPACE is ready"
      - name: operator-sdk-run-bundle
        image: quay.io/operator-framework/operator-sdk:latest
        env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
        - name: NAMESPACE
          value: "$(params.namespace)"
        volumeMounts:
        - name: credentials
          mountPath: /credentials
        script: |
          #!/bin/bash
          set -euo pipefail
          
          echo "Starting operator bundle installation..."
          echo "Bundle: $(params.bundleImage)"
          echo "Namespace: $NAMESPACE"
          echo "Timeout: $(params.installTimeout)"
          
          # Run operator-sdk and capture exit code, but don't fail the step
          if operator-sdk run bundle \
            --security-context-config restricted \
            --namespace "$NAMESPACE" \
            --timeout "$(params.installTimeout)" \
            "$(params.bundleImage)"; then
            
            echo "Operator bundle installation completed successfully!"
            echo "SUCCESS" > /credentials/operator-install-status
          else
            EXIT_CODE=$?
            echo "ERROR: operator-sdk run bundle failed with exit code $EXIT_CODE"
            echo "FAILED" > /credentials/operator-install-status
            # Don't exit here - let the debug step handle the failure
          fi
      - name: debug-operator-failure
        image: quay.io/konflux-ci/konflux-test:latest
        env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
        - name: NAMESPACE
          value: "$(params.namespace)"
        volumeMounts:
        - name: credentials
          mountPath: /credentials
        script: |
          #!/bin/bash
          set -euo pipefail
          
          # Check if operator installation failed
          if [ -f /credentials/operator-install-status ] && [ "$(cat /credentials/operator-install-status)" = "SUCCESS" ]; then
            echo "Operator installation succeeded, skipping debug collection"
            exit 0
          fi
          
          echo "=========================================="
          echo "DEBUGGING INFORMATION - OPERATOR INSTALLATION FAILED"
          echo "=========================================="
          
          echo "=== NAMESPACE STATUS ==="
          oc get namespace "$NAMESPACE" -o yaml || true
          
          echo "=== DEPLOYMENTS ==="
          oc get deployments -n "$NAMESPACE" -o wide || true
          
          echo "=== PODS ==="
          oc get pods -n "$NAMESPACE" -o wide || true
          
          echo "=== EVENTS ==="
          oc get events -n "$NAMESPACE" --sort-by=.metadata.creationTimestamp || true
          
          echo "=== CSVS ==="
          oc get csv -n "$NAMESPACE" -o wide || true
          
          echo "=== SUBSCRIPTIONS ==="
          oc get subscriptions -n "$NAMESPACE" -o wide || true
          
          echo "=== CATALOG SOURCES ==="
          oc get catalogsources -n "$NAMESPACE" -o wide || true
          
          echo "=== OPERATOR GROUPS ==="
          oc get operatorgroups -n "$NAMESPACE" -o wide || true
          
          echo "=== INSTALL PLANS ==="
          oc get installplans -n "$NAMESPACE" -o wide || true
          
          # Get detailed status of any failed pods
          echo "=== FAILED POD DETAILS ==="
          for pod in $(oc get pods -n "$NAMESPACE" --field-selector=status.phase=Failed -o name 2>/dev/null || true); do
            if [ -n "$pod" ]; then
              echo "--- Pod: $pod ---"
              oc describe "$pod" -n "$NAMESPACE" || true
              echo "--- Pod Logs: $pod ---"
              oc logs "$pod" -n "$NAMESPACE" --previous=true 2>/dev/null || true
              oc logs "$pod" -n "$NAMESPACE" 2>/dev/null || true
            fi
          done
          
          # Get details of pods that are not running
          echo "=== NON-RUNNING POD DETAILS ==="
          for pod in $(oc get pods -n "$NAMESPACE" --field-selector=status.phase!=Running,status.phase!=Succeeded -o name 2>/dev/null || true); do
            if [ -n "$pod" ]; then
              echo "--- Pod: $pod ---"
              oc describe "$pod" -n "$NAMESPACE" || true
              echo "--- Pod Logs: $pod ---"
              oc logs "$pod" -n "$NAMESPACE" --previous=true 2>/dev/null || true
              oc logs "$pod" -n "$NAMESPACE" 2>/dev/null || true
            fi
          done
          
          # Get CSV details if they exist
          echo "=== CSV DETAILS ==="
          for csv in $(oc get csv -n "$NAMESPACE" -o name 2>/dev/null || true); do
            if [ -n "$csv" ]; then
              echo "--- CSV: $csv ---"
              oc describe "$csv" -n "$NAMESPACE" || true
              oc get "$csv" -n "$NAMESPACE" -o yaml || true
            fi
          done
          
          echo "=========================================="
          echo "END DEBUGGING INFORMATION"
          echo "=========================================="
          
          # Re-exit with error to fail the task since operator installation failed
          exit 1
  - name: configure-keda
    runAfter:
    - deploy-operator
    taskSpec:
      params:
      - name: namespace
        type: string
      volumes:
      - name: credentials
        emptyDir: {}
      steps:
      - name: get-kubeconfig
        ref:
          resolver: git
          params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
        params:
        - name: eaasSpaceSecretRef
          value: $(tasks.provision-eaas-space.results.secretRef)
        - name: clusterName
          value: "$(tasks.provision-cluster.results.clusterName)"
        - name: credentials
          value: credentials
      - name: create-kedacontroller
        image: quay.io/konflux-ci/konflux-test:latest
        env:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
        - name: NAMESPACE
          value: "$(params.namespace)"
        volumeMounts:
        - name: credentials
          mountPath: /credentials
        script: |
          #!/bin/bash
          set -euxo pipefail
          echo "Creating KedaController instance in namespace: $NAMESPACE"
          oc apply -f - <<EOF
          apiVersion: keda.sh/v1alpha1
          kind: KedaController
          metadata:
            name: keda
            namespace: $NAMESPACE
          spec:
            metricsServer:
              logLevel: "0"
            operator:
              logEncoder: console
              logLevel: info
            serviceAccount: {}
            watchNamespace: ""
          EOF
          echo "Waiting for KEDA components to be ready..."
          timeout 300s bash -c "
            until [ \"\$(oc get deployment -n $NAMESPACE keda-metrics-apiserver -o jsonpath='{.status.conditions[?(@.type==\"Available\")].status}' 2>/dev/null)\" = \"True\" ]; do
              echo -n .
              sleep 5
            done
          "
          echo " keda-metrics-apiserver ready"
          timeout 300s bash -c "
            until [ \"\$(oc get deployment -n $NAMESPACE keda-operator -o jsonpath='{.status.conditions[?(@.type==\"Available\")].status}' 2>/dev/null)\" = \"True\" ]; do
              echo -n .
              sleep 5
            done
          "
          echo " keda-operator ready"
          echo "Custom Metrics Autoscaler Operator is ready!"
    params:
    - name: namespace
      value: "$(params.NAMESPACE)"
  - name: rapidast-check
    runAfter:
    - configure-keda
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/redhatproductsecurity/rapidast
      - name: revision
        value: development
      - name: pathInRepo
        value: examples/konflux/rapidast-check.yaml
    params:
    - name: KUBECONFIG_SECRET
      value: "$(tasks.provision-eaas-space.results.secretRef)"
    - name: PORT_FORWARD_TARGETS
      value: "service/keda-metrics-apiserver -n $(params.NAMESPACE) 9443:9443,service/keda-operator-metrics-service -n $(params.NAMESPACE) 8080:8080"
    - name: RAPIDAST_CONFIG_VALUE
      value: |
        config:
          configVersion: 6
          results:
            exclusions:
              rules:
                - name: "Exclude findings below a severity level of Important"
                  cel_expression: ".result.level != 'error' && .result.level != 'warning'"
        application:
          shortName: "custom-metrics-autoscaler-operator"
          url: "https://127.0.0.1:9443"
        scanners:
          zap:
            spider:
              maxDuration: 5
            passiveScan:
              maxDuration: 10
            activeScan:
              policy: API-scan-minimal
              maxDuration: 10
