apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-evidence-test
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "test-simple-evidence"
spec:
  description: |
    Step 2: Create evidence files AND build container using Konflux buildah-oci-ta.
    Now that file creation works, add proven container build pattern.
  params:
  - name: test-name
    type: string
    default: "evidence-container-build"
  - name: output-image
    type: string
    default: "quay.io/jkyros/custom-metrics-autoscaler-konflux-operator-bundle"
  - name: image-expires-after
    type: string
    default: "6h"
  tasks:
  
  # Clone repository to get build context (includes Dockerfile.evidence)
  - name: clone-source
    timeout: "10m"
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:be82c55346e8810bd1edc5547f864064da6945979baccca7dfc99990b392a02b
      - name: kind
        value: task
    params:
    - name: url
      value: "https://github.com/jkyros/cma-podauto-dast-integration.git"
    - name: revision
      value: "main"
    - name: ociStorage
      value: "$(params.output-image).git"
    - name: ociArtifactExpiresAfter
      value: "$(params.image-expires-after)"
  
  # Build evidence container using proven Konflux buildah-oci-ta task
  - name: build-evidence-container
    runAfter:
    - clone-source
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.4@sha256:d78d8abba7a84faa391d8b3b23be49ad8c09e9b1c0cabaed3919f64100cead2d
      - name: kind
        value: task
    params:
    - name: IMAGE
      value: "$(params.output-image):evidence-test-$(context.pipelineRun.name)"
    - name: DOCKERFILE
      value: "Dockerfile.evidence"
    - name: CONTEXT
      value: "."
    - name: HERMETIC
      value: "false"
    - name: IMAGE_EXPIRES_AFTER
      value: "$(params.image-expires-after)"
    - name: SOURCE_ARTIFACT
      value: "$(tasks.clone-source.results.SOURCE_ARTIFACT)"
    # buildah-oci-ta handles authentication automatically in Konflux